### ISSUE TITLE
Ошибки на этапе компиляции

### ISSUE THREAD

**Issue by d1sert** [Letomaniy/DeftHack-Unturned-OFFICIAL#1]
При компиляции vs сначала выдает еррорки после все таки компилирует и то криво то что по факту ничего и не компилируется, вот консоль: 
![изображение](https://user-images.githubusercontent.com/77913608/105660889-18b17b00-5edd-11eb-9928-8558ce7e3c0f.png)
Если проблема с библиотеками ещё я могу решить найдя и добавить в проект, то с функциями Sleek и SleekButton не понятно, пытался Assembly-CSharp и Assembly-CSharp-firstpass заменить на те что лежали в исходниках других читов, но когда идёт замена Sleek и SleekButton хоть и чинятся, но другие функции ломаются

**Comment by d1sert** [comment]
![изображение](https://user-images.githubusercontent.com/77913608/105662020-d3427d00-5edf-11eb-8654-907b2cf6e963.png)
Консоль, но уже после того как обновил input дллки и добавил недостающих

**Comment by Letomaniy** [comment]
> При компиляции vs сначала выдает еррорки после все таки компилирует и то криво то что по факту ничего и не компилируется, вот консоль:
> ![изображение](https://user-images.githubusercontent.com/77913608/105660889-18b17b00-5edd-11eb-9928-8558ce7e3c0f.png)
> Если проблема с библиотеками ещё я могу решить найдя и добавить в проект, то с функциями Sleek и SleekButton не понятно, пытался Assembly-CSharp и Assembly-CSharp-firstpass заменить на те что лежали в исходниках других читов, но когда идёт замена Sleek и SleekButton хоть и чинятся, но другие функции ломаются

Всё что касается Sleek больше не работает из-за обновления. Однако можешь SleekButton заменить на ISleekElement. Весь класс OV_PlayerDashboardInformationUI можешь закомментировать, ибо работать он не будет. После всего этого у тебя вылетит ещё ошибка в MirrorCameraComponent там не будет добавлятся компонент GUILayer, потому что он был вырезан из юнити на которой сейчас стоит игра. То есть строку с ошибкой там тоже закомментировать. Я это фиксить всё не буду потому что мне это не нужно)

**Comment by Letomaniy** [comment]
> При компиляции vs сначала выдает еррорки после все таки компилирует и то криво то что по факту ничего и не компилируется, вот консоль:
> ![изображение](https://user-images.githubusercontent.com/77913608/105660889-18b17b00-5edd-11eb-9928-8558ce7e3c0f.png)
> Если проблема с библиотеками ещё я могу решить найдя и добавить в проект, то с функциями Sleek и SleekButton не понятно, пытался Assembly-CSharp и Assembly-CSharp-firstpass заменить на те что лежали в исходниках других читов, но когда идёт замена Sleek и SleekButton хоть и чинятся, но другие функции ломаются

чуть не забыл... 
Будет ещё ошибка в OV_UseableGun, там будут три строки с ошибками. Все три строки нужно заменить на одну `PlayerLifeUI.hitmarkers[0].image.isVisible = false; `
