### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by d1sert** [Letomaniy/DeftHack-Unturned-OFFICIAL#2]
Появился вопрос по поводу файла с ассетами, можно ли его как нибудь открыть/декомпилировать?(И да, подождал минут 10 уже после запуска, f1 по прежнему не хочет работать)

**Comment by Letomaniy** [comment]
В связи с этим добавил инструкцию и пакет файлов в репозиторий.
 https://github.com/Letomaniy/DeftHack-Unturned-OFFICIAL/tree/master/Assets
