### ISSUE TITLE
Battleye bypass

### ISSUE THREAD

**Issue by doozzik** [Letomaniy/DeftHack-Unturned-OFFICIAL#3]
@Letomaniy Привет. Продаешь обход battleye для unturned? Мой бюджет 300$. Если да - мой дискорд uhack#6004

**Comment by Letomaniy** [comment]
Я сам не ищу обходов. Но знаю что один человек обошёл анти чит. Могу только примерно рассказать как. За чисто символические 10$))))

**Comment by doozzik** [comment]
Если там не вариант с iobit unlocker (удаление файлов уже не работает) и не нужно писать свой драйвер на c++, тогда меня устраивает :)

**Comment by Letomaniy** [comment]
Ну две новости. Одна плохая другая лучше. 
1) Драйвер писать не нужно будет
2) что-то на C++ всё же написать(или исправить) придётся

А обход с анлокером уже не работает второй год.

**Comment by doozzik** [comment]
Устраивает. Перейдем в дискорд или почту? uhack#6004 или doozzik@gmail.com
